### ISSUE TITLE
How much testing demo should I expect to be able to try out?

### ISSUE THREAD

**Issue by ZYinMD** [adyen-examples/adyen-react-online-payments#2]
I ran the dev server and visited `localhost:8080`, and wasn't able to do much except clicking on the cards, not sure if that's expected.

So, this is what I did:
1. follow the instructions [here](https://docs.adyen.com/checkout/get-started?tab=node_js_6#step-3-make-a-test-payment) to use `curl` to test my api key and merchant account. Test passed.
1. clone this repo, set values in `.env`. (Note that the `CLIENT_KEY` was not mentioned and not tested in step 1, but I clicked "Generate New Client Key" anyway, and added the generated client key in the `.env`.)
1. `npm run dev`, then visit `localhost:8080/`.
1. click on the cards, for instance "Drop In", then try different payment methods.

Every payment methods seem to display with some error message. Is that expected? For instance, the credit card input fields show "Please check origin key":
![image](https://user-images.githubusercontent.com/32368482/89724788-7dcbef80-d9d5-11ea-8263-356c069e7597.png)

And Alipay redirects to this page (I did have Alipay enabled in my merchant account):
![image](https://user-images.githubusercontent.com/32368482/89724775-59701300-d9d5-11ea-8da0-3cd9a8c035b4.png)

**Comment by deepu105** [comment]
Hi @ZYinMD sorry that you are facing issues. These should have worked when the configuration of your merchant account is done correctly. I'll try to help you here. I need some more information. What payment methods did you face issues (I see credit card and Alipay above)

1. For credit card did you add the domain (localhost:8080) to the client key that you created?
2. For Alipay you need to do some additional configuration with the help of support, can you reach out to support so that they can do these for you

**Comment by ZYinMD** [comment]
Hi deepu105, thanks for helping!

So, I tested all payment methods, here are the results:
- most payment methods do work
- `Please check origin key` error: credit cards, BanContact card
- Error message after redirect: Klarna, Alipay, Wechat.

About adding `locahost:8080` to the client key: Could you point me to the doc where it's mentioned ? Sorry I haven't read the majority of the doc, the reading path I followed was 1. read the [Get Started](https://docs.adyen.com/checkout/get-started) , and 2. at [the bottom](https://docs.adyen.com/checkout/get-started?tab=node_js_6#recommended-clone-our-example-integration-4) of the Get Started page, found the link to this repo, and 3. come to this repo and read README.

About additional help from support for Alipay: thanks I'll reach out to them. Does Klarna and Wechat have similar problems?

**Comment by deepu105** [comment]
Hi @ZYinMD 

For client key to work you need to add the origins you are using in the customer area, you don't have to regenerate the client key you can just add the origins following [this doc ](https://docs.adyen.com/development-resources/client-side-authentication)and after few seconds it should work.

This demo is configured to work only for below payment methods as some payment methods need special handling in code and we are slowly adding support as required in demos. When you use drop-in it will display all the payment methods that you have enabled but they might not work unless the backend is configured to handle special cases.
- Card
- iDEAL
- giropay
- Dotpay
- EPS
- SOFORT
- Bancontact card
- Paysafe card

If you want to try Alipay/Klarna I suggest checking out https://github.com/adyen-examples/adyen-node-online-payments which has an implementation for these and the changes are only on the backend and both these demos have a very similar nodeJS backend. For Alipay you might have to contact support to enable it as it has some limitations on test accounts due to how Alipay works. Hope this helps. Let me know if you have any more questions

**Comment by ZYinMD** [comment]
It's now working! Thanks for your help!

It may be a good idea to mention setting the "allowed origin" in README.

**Comment by deepu105** [comment]
@ZYinMD thanks for suggestion, the client key docs are linked in Readme, but i'll add a mention of origins explicitly as well
