### ISSUE TITLE
Can you provide an official test account？

### ISSUE THREAD

**Issue by Deja-vuuu** [adyen-examples/adyen-react-online-payments#51]
I tried several registered test users, and the result prompting the form of submission of the form failed！

I don't know where the problem is ~

**Comment by jlengrand** [comment]
Hey @Deja-vuuu, which form do you mean ? Would you posting a link to it here please? 

We actually cannot really provide an official test account because you could potentially add personally identifiable information in it (like your credit card number) which could then be visible by other people. 

What we can (and possibly should) be doing though is making it easier to create test accounts. Please send me the link and I'll have a look
